<<<<<<< HEAD
theme: jekyll-theme-cayman

title: [Value-Driven Evaluation of Visualizations]
description: [Methodology Description, Materials, and Results]
=======
>>>>>>> 6078d8bf6aa7a597cd4495aea2486e3e2ef98636
